#!/bin/bash

RED='\e[91m'
BRED='\e[41m'
GREEN='\e[32m'
NC='\e[0m' # No Color

# Return where the bash script is located
DIRDEV="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
cd ..
if [ -z $1 ]
then
	# not forced
	sh deploy
else
	# forced
	sh deploy force
fi
cd $DIR
